// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "pb.StringMessage")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xdd, 0x55, 0xab, 0x8e, 0xb6, 0xd4, 0x54, 0x50, 0x17, 0xc5, 0x52, 0x10, 0x14, 0xec,
	0xa6, 0xad, 0x37, 0x6f, 0x15, 0x3c, 0x89, 0x17, 0x7b, 0x10, 0xbc, 0x65, 0xc3, 0x34, 0x8d, 0x6c,
	0x93, 0x90, 0xa4, 0xf5, 0x1f, 0x5e, 0x7c, 0x84, 0xfa, 0x5e, 0x5e, 0x7c, 0x05, 0x1f, 0x44, 0x9a,
	0x82, 0xb0, 0xac, 0x07, 0x4f, 0xc3, 0x37, 0x7c, 0xfc, 0x7e, 0xc3, 0x40, 0xc3, 0x58, 0xed, 0x35,
	0x75, 0x68, 0xa7, 0x92, 0x63, 0x1a, 0x12, 0x89, 0x4d, 0x96, 0x1c, 0x08, 0xad, 0x45, 0x8e, 0x94,
	0x19, 0x49, 0x99, 0x52, 0xda, 0x33, 0x2f, 0xb5, 0x72, 0x8b, 0x46, 0x72, 0x16, 0x06, 0x6f, 0x0b,
	0x54, 0x6d, 0xf7, 0xc8, 0x84, 0x40, 0x4b, 0xb5, 0x09, 0x8d, 0x72, 0xbb, 0x75, 0x0c, 0xd5, 0x81,
	0xb7, 0x52, 0x89, 0x1b, 0x74, 0x8e, 0x09, 0x24, 0x3b, 0xb0, 0x3a, 0x65, 0xf9, 0x04, 0xf7, 0xa2,
	0x66, 0x74, 0xb2, 0x71, 0xbb, 0x08, 0xbd, 0xcf, 0x08, 0x36, 0xaf, 0xf8, 0x48, 0x0f, 0x16, 0xc7,
	0x90, 0x3b, 0x58, 0x99, 0x47, 0xb2, 0x9d, 0x9a, 0x2c, 0x2d, 0x00, 0x92, 0xf2, 0xaa, 0x75, 0x3a,
	0xeb, 0xd7, 0xb2, 0x2d, 0x00, 0xa8, 0xf4, 0x8d, 0xbc, 0xc6, 0x67, 0xb2, 0xf4, 0xfe, 0xf5, 0xfd,
	0x11, 0x13, 0x52, 0xa7, 0xd3, 0x2e, 0x45, 0x3e, 0xd2, 0xf4, 0x35, 0x78, 0xde, 0xc8, 0x10, 0x20,
	0x78, 0xbc, 0x45, 0x36, 0xfe, 0x27, 0xbe, 0xf3, 0x37, 0x7e, 0x9f, 0xec, 0xce, 0xf1, 0x2e, 0xa0,
	0x0a, 0x96, 0x4e, 0x74, 0x39, 0x9c, 0xf5, 0x39, 0xa9, 0xc1, 0x1a, 0x3e, 0xb1, 0xb1, 0xc9, 0xb1,
	0xb7, 0xdc, 0x4d, 0x3b, 0xbd, 0x3a, 0x33, 0x26, 0x97, 0x3c, 0x3c, 0x88, 0x3e, 0x38, 0xad, 0x2e,
	0x4a, 0x9b, 0xfb, 0x23, 0x38, 0xfc, 0xf5, 0x34, 0xd6, 0xe3, 0xa4, 0xca, 0x26, 0x7e, 0xa4, 0xad,
	0x7c, 0x09, 0x9d, 0x66, 0x5c, 0x3c, 0x24, 0xab, 0x84, 0x37, 0x9f, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xb9, 0x85, 0x55, 0x88, 0xcd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoServiceClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
	EchoStream(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (EchoService_EchoStreamClient, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/pb.EchoService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) EchoStream(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (EchoService_EchoStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EchoService_serviceDesc.Streams[0], "/pb.EchoService/EchoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoServiceEchoStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EchoService_EchoStreamClient interface {
	Recv() (*StringMessage, error)
	grpc.ClientStream
}

type echoServiceEchoStreamClient struct {
	grpc.ClientStream
}

func (x *echoServiceEchoStreamClient) Recv() (*StringMessage, error) {
	m := new(StringMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServiceServer is the server API for EchoService service.
type EchoServiceServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	EchoStream(*StringMessage, EchoService_EchoStreamServer) error
}

// UnimplementedEchoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEchoServiceServer struct {
}

func (*UnimplementedEchoServiceServer) Echo(ctx context.Context, req *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedEchoServiceServer) EchoStream(req *StringMessage, srv EchoService_EchoStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EchoStream not implemented")
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_EchoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StringMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServiceServer).EchoStream(m, &echoServiceEchoStreamServer{stream})
}

type EchoService_EchoStreamServer interface {
	Send(*StringMessage) error
	grpc.ServerStream
}

type echoServiceEchoStreamServer struct {
	grpc.ServerStream
}

func (x *echoServiceEchoStreamServer) Send(m *StringMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EchoStream",
			Handler:       _EchoService_EchoStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
